theme: jekyll-theme-cayman
title: Brian's Blog
description: This is a IT related blog maintained by Brian
google_analytics: UA-131234157-1
gitalk:
  clientID: 9e983ec74994d58944b5
  clientSecret: c806582d29fe885c189f9a04196ea6bd12ea02c6
  repo: ChenWenBrian.github.io
  owner: ChenWenBrian
  admin: ["ChenWenBrian"] # Ensure uniqueness and length less than 50
  id: location.pathname
  distractionFreeMode: false  # Facebook-like distraction free mode
